language: go
go: release
before_install:
  - gocleandeps=c16c849abae90c23419d
  - git clone https://gist.github.com/$gocleandeps.git
  - goclean=71d0380287747d956a26
  - git clone https://gist.github.com/$goclean.git
install:
  - go get -d -t -v ./...
  - bash $gocleandeps/gocleandeps.sh
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - bash $goclean/goclean.sh
after_success:
  - goveralls -coverprofile=profile.cov -service=travis-ci
