language: go
go:
  - 1.3
  - release
  - tip
before_install:
  - gotools=golang.org/x/tools
  - if [ "$TRAVIS_GO_VERSION" = "release" ] || [ "$TRAVIS_GO_VERSION" = "go1.3.3" ]; then gotools=code.google.com/p/go.tools; fi
install:
  - go get -d -t -v ./...
  - go get $gotools/cmd/vet
  - go get -v github.com/GeertJohan/fgt
  - go get -v github.com/golang/lint/golint
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - go vet
  - fgt golint -min_confidence=0.9 .
  - go test -v
